/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as MyCasesRouteImport } from './routes/my-cases'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as ReferralVisitIdRouteImport } from './routes/referral.$visitId'
import { Route as ReviewVisitIdRouteImport } from './routes/review.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCasesRoute = MyCasesRouteImport.update({
  id: '/my-cases',
  path: '/my-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralVisitIdRoute = ReferralVisitIdRouteImport.update({
  id: '/referral/$visitId',
  path: '/referral/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewVisitIdRoute = ReviewVisitIdRouteImport.update({
  id: '/review/$visitId',
  path: '/review/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/care-plans': typeof CarePlansRoute
  '/doctor': typeof DoctorRoute
  '/followups': typeof FollowupsRoute
  '/history': typeof HistoryRoute
  '/hospitals': typeof HospitalsRoute
  '/intake': typeof IntakeRoute
  '/medicines': typeof MedicinesRoute
  '/my-cases': typeof MyCasesRoute
  '/queue': typeof QueueRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/trends': typeof TrendsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/referral/$visitId': typeof ReferralVisitIdRoute
  '/review/$visitId': typeof ReviewVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/care-plans': typeof CarePlansRoute
  '/doctor': typeof DoctorRoute
  '/followups': typeof FollowupsRoute
  '/history': typeof HistoryRoute
  '/hospitals': typeof HospitalsRoute
  '/intake': typeof IntakeRoute
  '/medicines': typeof MedicinesRoute
  '/my-cases': typeof MyCasesRoute
  '/queue': typeof QueueRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/trends': typeof TrendsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/referral/$visitId': typeof ReferralVisitIdRoute
  '/review/$visitId': typeof ReviewVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/care-plans': typeof CarePlansRoute
  '/doctor': typeof DoctorRoute
  '/followups': typeof FollowupsRoute
  '/history': typeof HistoryRoute
  '/hospitals': typeof HospitalsRoute
  '/intake': typeof IntakeRoute
  '/medicines': typeof MedicinesRoute
  '/my-cases': typeof MyCasesRoute
  '/queue': typeof QueueRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/trends': typeof TrendsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/referral/$visitId': typeof ReferralVisitIdRoute
  '/review/$visitId': typeof ReviewVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/care-plans'
    | '/doctor'
    | '/followups'
    | '/history'
    | '/hospitals'
    | '/intake'
    | '/medicines'
    | '/my-cases'
    | '/queue'
    | '/referrals'
    | '/settings'
    | '/tracker'
    | '/trends'
    | '/patients/$patientId'
    | '/referral/$visitId'
    | '/review/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/care-plans'
    | '/doctor'
    | '/followups'
    | '/history'
    | '/hospitals'
    | '/intake'
    | '/medicines'
    | '/my-cases'
    | '/queue'
    | '/referrals'
    | '/settings'
    | '/tracker'
    | '/trends'
    | '/patients/$patientId'
    | '/referral/$visitId'
    | '/review/$visitId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/care-plans'
    | '/doctor'
    | '/followups'
    | '/history'
    | '/hospitals'
    | '/intake'
    | '/medicines'
    | '/my-cases'
    | '/queue'
    | '/referrals'
    | '/settings'
    | '/tracker'
    | '/trends'
    | '/patients/$patientId'
    | '/referral/$visitId'
    | '/review/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CarePlansRoute: typeof CarePlansRoute
  DoctorRoute: typeof DoctorRoute
  FollowupsRoute: typeof FollowupsRoute
  HistoryRoute: typeof HistoryRoute
  HospitalsRoute: typeof HospitalsRoute
  IntakeRoute: typeof IntakeRoute
  MedicinesRoute: typeof MedicinesRoute
  MyCasesRoute: typeof MyCasesRoute
  QueueRoute: typeof QueueRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  TrackerRoute: typeof TrackerRoute
  TrendsRoute: typeof TrendsRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  ReferralVisitIdRoute: typeof ReferralVisitIdRoute
  ReviewVisitIdRoute: typeof ReviewVisitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-cases': {
      id: '/my-cases'
      path: '/my-cases'
      fullPath: '/my-cases'
      preLoaderRoute: typeof MyCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral/$visitId': {
      id: '/referral/$visitId'
      path: '/referral/$visitId'
      fullPath: '/referral/$visitId'
      preLoaderRoute: typeof ReferralVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$visitId': {
      id: '/review/$visitId'
      path: '/review/$visitId'
      fullPath: '/review/$visitId'
      preLoaderRoute: typeof ReviewVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CarePlansRoute: CarePlansRoute,
  DoctorRoute: DoctorRoute,
  FollowupsRoute: FollowupsRoute,
  HistoryRoute: HistoryRoute,
  HospitalsRoute: HospitalsRoute,
  IntakeRoute: IntakeRoute,
  MedicinesRoute: MedicinesRoute,
  MyCasesRoute: MyCasesRoute,
  QueueRoute: QueueRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  TrackerRoute: TrackerRoute,
  TrendsRoute: TrendsRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  ReferralVisitIdRoute: ReferralVisitIdRoute,
  ReviewVisitIdRoute: ReviewVisitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
